title      : Rare计划官网
lang       : zh-CN
description: 我们打造最棒的手表应用
copyright  : <a href="https://icp.gov.moe/?keyword=20232880" target="_blank">萌ICP备20232880号</a> © 2023 - 2026 秋冥散雨_GenOuka All Rights Reserved
extra      : 本网站属于非盈利性质网站，不进行任何商业经营活动。

nav:
 - name: 首页
   link: /
 - name: 开发文档
   link: https://github.com/Genouka/rareplan_docs
 - name: 联系方式
   link: /lianxi/
 - name: 法律信息
   link: /law/

links:
 - name: 【官方】秋冥散雨_GenOuka的项目索引站
   link: https://genouka.top/
 - name: 【官方】鸿蒙织月计划官网
   link: https://zhiyue.genouka.top/
 - name: 【友链】中国独立开发者项目列表
   link: https://github.com/1c7/chinese-independent-developerxi/
